package zengine;

/*
 * Change so that it holds Phrases instead?
 */
import zengine.grammar.*;
import java.util.ArrayList;


/**
* Represents a Sentence, ie, a complete command, parsed and ready to execute. 
*/
public class Sentence extends Grammar
{
	
	private Grammar current;

	/**
	* Constructor is private; new instances are generated by getSentence
	*/
	private Sentence(Class c, Grammar g)
	{
		super();
		acceptable.add(Verb.class);
		acceptable.add(Direction.class);
		current = g;
		complements.put(c.getName(), g);
		Utils.debug("initiated Sentence with "+g.toString());
	}



	/**
	*	Returns an instance with a verb or a Direction as its head. 
	* 	A sentence should really only be generated by the Parser, I think. I may
	* 	be wrong, but in any case, it should not be generated from outside this
	* 	package. 
	*/
	protected static Sentence getSentence(Grammar g)
	{
			if (Verb.class.isAssignableFrom(g.getClass()))
			{
				return new Sentence(Verb.class,g);
			}
			if (Direction.class.isAssignableFrom(g.getClass()))
			{
				return new Sentence(Direction.class, g);
			}

		return null;
	}

	
	/**
	*	Attempts to apply argument to the current Grammar object. If that object
	*	wants a g, the argument is applied and the method returns true. If not,
	*	the method returns false and this sentence is spoiled. 
	*/
	public boolean accept(Grammar g)
	{
		StringBuffer sb= new StringBuffer();
                
                boolean accepted = current.accept(g);
		for(String s: complements.keySet())
		{
                        
			sb.append(complements.get(s).toString());
		}
	
		Utils.debug("Sentence.accept("+g.toString()+") complements = "+
			sb.toString()+ " current = " +current);
			
		if (current == null) return false;

		//boolean accepted = current.accept(g); 

	 	if (accepted)
		{
			Utils.debug("accepted " + g.toString());
			Utils.debug(g.getClass().toString());
			current=g;

			sb= new StringBuffer();
      	for(String s: complements.keySet())
      	{
        		 sb.append(complements.get(s).toString());
      	}

			Utils.debug("Result = true. Complements = "+ sb.toString());
			return true;
			

		}
		else 
		{	
			System.out.println("Result = false");
			return false;
		}

	}
	

	/**
	*	Perform the action represented by this sentence. execute simply passes an
	*	execute() message to the head of this sentence; it is assumed that that
	*	object knows what to do. 
	*/	
	protected void execute()
	{
		for (String s: complements.keySet())
		{
			complements.get(s).execute();
		}
	}


}
